# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/awalsh128/cache-apt-pkgs-action
#   - https://github.com/prefix-dev/setup-pixi
#   - https://github.com/actions/upload-artifact

name: ci-tests-lock

on:
  workflow_dispatch:
  schedule:
    # every day @ 00h03 except sunday (see ci-locks.yml)
    - cron: "3 0 * * 1-6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-lock:
    name: "test lock (${{ matrix.version }})"
    runs-on: "${{ matrix.os }}"

    env:
      ENV_NAME: "ci-tests-lock"
      PY_COLORS: "1"

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        version: ["py312"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "environment configure"
        env:
          # Maximum cache period (in weeks) before forcing a cache refresh.
          CACHE_WEEKS: 2
        run: |
          echo "CACHE_PERIOD=$(date +%Y).$(expr $(date +%U) / ${CACHE_WEEKS})" >> ${GITHUB_ENV}
          echo "NAME=geovista-${{ matrix.version }}" >> ${GITHUB_ENV}

      - name: "apt cache"
        uses: awalsh128/cache-apt-pkgs-action@7ca5f46d061ad9aa95863cd9b214dd48edef361d
        with:
          packages: libgl1-mesa-glx xvfb
          version: 1.0

      - name: "setup pixi"
        uses: prefix-dev/setup-pixi@14c8aabd75893f83f4ab30c03e7cf853c8208961
        with:
          cache-write: false
          run-install: false

      - name: "refresh pixi manifest"
        run: |
          pixi update --json | pixi exec pixi-diff-to-markdown > diff.md

      - name: "upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: lock-artifacts-${{ github.job }}-${{ strategy.job-index }}
          path: |
            ${{ github.workspace }}/diff.md
            ${{ github.workspace }}/pixi.lock

      - name: "cartopy cache"
        uses: ./.github/workflows/composite/cartopy-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}
          env_name: ${{ env.ENV_NAME }}

      - name: "geovista cache"
        uses: ./.github/workflows/composite/geovista-cache
        with:
          cache_period: ${{ env.CACHE_PERIOD }}

      - name: "test lock (${{ matrix.version }})"
        run: |
          pixi run --frozen --environment ${{ env.NAME }} pytest --xvfb-backend xvfb --fail_extra_image_cache --generated_image_dir test_images

      - name: "report failure"
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE="chore: pixi.lock test failure"
          BODY=$(cat <<EOL
          The \`${{ matrix.version }}\` tests for the latest resolved \`pixi.lock\` have failed for the \`${{ env.NAME }}\` environment.

          Please investigate GHA run-id [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          EOL
          )
          gh issue create --title "${TITLE}" --body "${BODY}" --label "bot" --label "new: issue" --repo "${{ github.repository }}"
